-- CREATE
-- Table: public.user
-- DROP TABLE IF EXISTS public."user";
CREATE TABLE IF NOT EXISTS public."user"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    birthday date,
    first_name character varying(255) COLLATE pg_catalog."default",
    gender character varying(255) COLLATE pg_catalog."default",
    last_name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT user_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."user"
    OWNER to postgres;

-- Table: public.disease
-- DROP TABLE IF EXISTS public.disease;
CREATE TABLE IF NOT EXISTS public.disease
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT disease_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.disease
    OWNER to postgres;

-- Table: public.risk_factor
-- DROP TABLE IF EXISTS public.risk_factor;
CREATE TABLE IF NOT EXISTS public.risk_factor
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT risk_factor_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.risk_factor
    OWNER to postgres;

-- Table: public.user_disease
-- DROP TABLE IF EXISTS public.user_disease;
CREATE TABLE IF NOT EXISTS public.user_disease
(
    id_disease integer NOT NULL,
    id_user integer NOT NULL,
    active boolean,
    CONSTRAINT user_disease_pkey PRIMARY KEY (id_disease, id_user),
    CONSTRAINT fk5ew2lshs6v67iwk0qf0jtx2gx FOREIGN KEY (id_user)
        REFERENCES public."user" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkby1i6ty2km4bu93yb7b3g7hft FOREIGN KEY (id_disease)
        REFERENCES public.disease (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.user_disease
    OWNER to postgres;

-- Table: public.user_risk_factor
-- DROP TABLE IF EXISTS public.user_risk_factor;
CREATE TABLE IF NOT EXISTS public.user_risk_factor
(
    id_risk_factor integer NOT NULL,
    id_user integer NOT NULL,
    active boolean,
    value integer,
    CONSTRAINT user_risk_factor_pkey PRIMARY KEY (id_risk_factor, id_user),
    CONSTRAINT fk52krgyexfkqnvao6lq7fq18f3 FOREIGN KEY (id_user)
        REFERENCES public."user" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkaci240lshyp852roe2etujke8 FOREIGN KEY (id_risk_factor)
        REFERENCES public.risk_factor (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.user_risk_factor
    OWNER to postgres;


--VALORES
INSERT INTO public."user"(
    id, first_name, last_name, gender, birthday)
    VALUES
    (1, 'Ivan', 'Valadez', 'male', '1986-02-09'),
    (2, 'Rosa', 'Gonzales', 'female', '1990-04-12'),
    (3, 'Carlos', 'Gamboa', 'male', '1994-06-03'),
    (4, 'Jose', 'Amante', 'male', '1998-12-01'),
    (5, 'Monserrat', 'Rodriguez', 'female', '1996-01-02'),
    (6, 'Alberto', 'Almeida', 'male', '2000-02-04'),
    (7, 'Lorena', 'Espinoza', 'female', '2008-03-06'),
    (8, 'Hugo', 'Castañeda', 'male', '1999-05-08'),
    (9, 'Walter', 'Corona', 'male', '2012-06-10'),
    (10, 'Francisco', 'Perez', 'male', '2002-07-23')
;

INSERT INTO public.disease(
    id, name)
    VALUES
    (1, 'diabetes'),
    (2, 'cardiovascular')
;

INSERT INTO public.risk_factor(
    id, name)
    VALUES
    (1, 'central_obesity'),
    (2, 'triglycerides'),
    (3, 'hdl'),
    (4, 'blood_pressure'),
    (5, 'plasma_glucose')
;

INSERT INTO public.user_risk_factor(
    id_user, id_risk_factor, value, active)
    VALUES
  --(ID,IDUSER,IDRISKFACTOR,VALUE,ACTIVE)
    -- Ivan Si
    (1, 1, 90, TRUE),
    (1, 2, 150, TRUE),
    (1, 3, 40, FALSE),
    (1, 4, 130, TRUE),
    (1, 5, 100, TRUE),
    -- Rosa Si
    (2, 1, 80, TRUE),
    (2, 2, 150, TRUE),
    (2, 3, 50, TRUE),
    (2, 4, 130, TRUE),
    (2, 5, 100, TRUE),
    -- Carlos No
    (3, 1, 92, TRUE),
    (3, 2, 152, TRUE),
    (3, 3, 35, FALSE),
    (3, 4, 100, FALSE),
    (3, 5, 101, FALSE),
    -- Jose Si
    (4, 1, 95, TRUE),
    (4, 2, 158, TRUE),
    (4, 3, 42, TRUE),
    (4, 4, 128, FALSE),
    (4, 5, 102, FALSE),
    -- Montserrat Si
    (5, 1, 81, TRUE),
    (5, 2, 150, TRUE),
    (5, 3, 51, TRUE),
    (5, 4, 132, TRUE),
    (5, 5, 98, TRUE),
    -- Alberto No
    (6, 1, 90, TRUE),
    (6, 2, 148, FALSE),
    (6, 3, 40, FALSE),
    (6, 4, 126, FALSE),
    (6, 5, 101, FALSE),
    -- Lorena Si
    (7, 1, 82, TRUE),
    (7, 2, 150, TRUE),
    (7, 3, 40, FALSE),
    (7, 4, 128, FALSE),
    (7, 5, 100, TRUE),
    -- Hugo Si
    (8, 1, 95, TRUE),
    (8, 2, 148, FALSE),
    (8, 3, 40, FALSE),
    (8, 4, 138, TRUE),
    (8, 5, 105, TRUE),
    -- Walter No
    (9, 1, 80, FALSE),
    (9, 2, 140, FALSE),
    (9, 3, 40, FALSE),
    (9, 4, 100, FALSE),
    (9, 5, 90, TRUE),
    -- Francisco Si
    (10, 1, 91, TRUE),
    (10, 2, 150, TRUE),
    (10, 3, 40, FALSE),
    (10, 4, 127, FALSE),
    (10, 5, 98, TRUE)
;

INSERT INTO public.user_disease(
    id_user, id_disease, active)
    VALUES
  --(ID,IDUSER,IDDISEASE,ACTIVE)
    -- Ivan Si
    (1, 1, TRUE),
    (1, 2, TRUE),
    -- Rosa Si
    (2, 1, TRUE),
    (2, 2, FALSE),
    -- Carlos No
    (3, 1, FALSE),
    (3, 2, FALSE),
    -- Jose Si
    (4, 1, FALSE),
    (4, 2, TRUE),
    -- Montserrat Si
    (5, 1, TRUE),
    (5, 2, TRUE),
    -- Alberto No
    (6, 1, FALSE),
    (6, 2, FALSE),
    -- Lorena Si
    (7, 1, TRUE),
    (7, 2, FALSE),
    -- Hugo Si
    (8, 1, TRUE),
    (8, 2, FALSE),
    -- Walter No
    (9, 1, FALSE),
    (9, 2, FALSE),
    -- Francisco Si
    (10, 1, FALSE),
    (10, 2, TRUE)
;
